#spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/student}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/student}
spring.datasource.username=${DB_USERNAME:jai.karvir}
spring.datasource.password=${DB_PASSWORD:}
# Entity ??? ??? ???? ??? ?? / ??
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

school.client.base-url=${SCHOOL_CLIENT_BASE_URL:https://jsonplaceholder.typicode.com}